### ISSUE TITLE
Migration to openssl 3.0

### ISSUE THREAD

**Issue by bighans** [galets/oneway-cpp#2]
Very well written, but are you able to upgrade to openssl api ver 3.0?

**Comment by galets** [comment]
May I ask what is the use case, why is the openssl upgrade necessary?

**Comment by galets** [comment]
I verified that application compiles and links with openssl 3.0.2 (with deprecation warnings). This issue needs no action. @bighans if there is a compelling reason to upgrade, please specify it and reopen the ticket.
